//app routes
const String ROUTE_INDEX = "/";
const String ROUTE_WELCOME = "/welcome";
const String ROUTE_LANGUAGE = "/language";
const String ROUTE_PROFILE = "/profile";
const String ROUTE_DASHBOARD = "/dashboard";
const String ROUTE_ADD_PRODUCT = "/addProduct";
const String ROUTE_LOGIN = "/login";
const String ROUTE_SEARCH_LOGOUT = "/searchLogout";

//db app configs
const String DB_TOKEN_CONFIG = "DB_TOKEN_CONFIG";
const String DB_APP_NAME_CONFIG = "DB_APP_NAME_CONFIG";
const String DB_ROOT_PAGE_ITEM_SELECTED_CONFIG =
    "DB_ROOT_PAGE_ITEM_SELECTED_CONFIG";
const String DB_LOGIN_PAGE_ITEM_SELECTED_CONFIG =
    "DB_LOGIN_PAGE_ITEM_SELECTED_CONFIG";
const String DB_LOGIN_PAGE_ITEM_SELECTED_CONFIG_MAIL_VALUE = "mail";
const String DB_LOGIN_PAGE_ITEM_SELECTED_CONFIG_PHONE_VALUE = "phone";
const String DB_LANGUAGE_CODE_CONFIG = "DB_LANGUAGE_CODE_CONFIG";
const String DB_COUNTRY_CODE_CONFIG = "DB_COUNTRY_CODE_CONFIG";
const String DB_API_HOST_IP_CONFIG = "DB_API_HOST_IP_CONFIG";
const String DB_USER_INFO_CONFIG = "DB_USER_INFO_CONFIG";
const String DB_BROKER_HOST_IP_CONFIG = "DB_BROKER_HOST_IP_CONFIG";
const String DB_BROKER_WS_PORT_CONFIG = "DB_BROKER_WS_PORT_CONFIG";
const String DB_APP_ID_CONFIG = "DB_APP_ID_CONFIG";
const String DB_LAST_PROVINCE_OFFSET_CONFIG = "DB_LAST_PROVINCE_CHANGE_CONFIG";
const String DB_LAST_PROVINCE_OFFSET_CONFIG_VALUE = "1970-01-01T00:00:00Z"; // epoch time
const String DB_LAST_CATEGORY_OFFSET_CONFIG = "DB_LAST_CATEGORY_OFFSET_CONFIG";
const String DB_LAST_CATEGORY_OFFSET_CONFIG_VALUE = "1970-01-01T00:00:00Z"; // epoch time
const String DB_API_HOST_IP_CONFIG_VALUE = "192.168.1.104:8000";
const String DB_BROKER_HOST_IP_CONFIG_VALUE = "192.168.1.104";
const String DB_BROKER_WS_PORT_CONFIG_VALUE = "1883";
const String DB_APP_IN_FIRST_CONFIG_TRUE = "DB_APP_IN_FIRST_CONFIG_TRUE";
const String DB_APP_IN_FIRST_CONFIG_FALSE = "DB_APP_IN_FIRST_CONFIG_FALSE";
const String DB_APP_IN_FIRST_CONFIG = "DB_APP_IN_CONFIG";

//db tables
const String DB_TABLE_CONFIGS = "t_configs";
const String DB_TABLE_OWN_PRODUCTS = "t_own_products";
const String DB_TABLE_PROVINCES = "t_provinces";
const String DB_TABLE_CATEGORIES = "t_categories";

//Payload types
const String PAYLOAD_TYPE_PROVINCE = "PAYLOAD_TYPE_PROVINCE";
const String PAYLOAD_TYPE_PRODUCT = "PAYLOAD_TYPE_PRODUCT";
const String PAYLOAD_TYPE_CATEGORY = "PAYLOAD_TYPE_CATEGORY";





